name: Build & Push COVA Digital Image

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute version/tag
        id: vars
        run: |
          echo "containerver=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"

      - name: Compute lowercase owner
        id: owner
        run: |
          echo "lower_owner=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"

      - name: Build & Push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.dev
          push: true
          provenance: false
          sbom: false
          platforms: linux/amd64,linux/arm64
          build-args: |
            NEXT_PUBLIC_VERSION=${{ steps.vars.outputs.containerver }}
          tags: |
            ghcr.io/${{ steps.owner.outputs.lower_owner }}/postiz-app:${{ steps.vars.outputs.containerver }}
            ghcr.io/${{ steps.owner.outputs.lower_owner }}/postiz-app:latest
